services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: traffic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redpanda:
    image: redpandadata/redpanda:latest
    command: ["redpanda", "start", "--overprovisioned", "--smp 1", "--memory 1G", "--reserve-memory 0M", "--node-id 0", "--advertise-kafka-addr", "redpanda:9092"]
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8081:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'redpanda:9092'
      KAFKA_CLUSTERS_0_ZOOKEEPER: ''

volumes:
  db-data:
