server:
  port: 8081

spring:
  application:
    name: utility-service
  datasource:
    url: jdbc:mysql://localhost:3306/water_electricity_management?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: nassim123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: wem-claims-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.smartcity.kafka.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

kafka:
  consumer:
    group-id: wem-claims-group
  topics:
    incoming: claims.WEM
    responses: claims.responses
    status-updates: claims.status-updates

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
  instance:
    prefer-ip-address: true
